### ISSUE TITLE
Suggestion: Filter for waterproof level

### ISSUE THREAD

**Issue by jrussell11** [bucherfa/lineageos-devices#1]
As a user, I'd like to filter down to just devices that are waterproof.

**Comment by bucherfa** [comment]
Thanks for the suggestion.

Currently I am just using the data that is made available by the LineageOS Project. Unfortunately waterproof level is not included. https://github.com/LineageOS/lineage_wiki/tree/master/_data/devices

To add this property to each device, I would need to get the data from an up-to-date reliable source that also permits the usage of that data. Could you point me to one?

**Comment by bucherfa** [comment]
waterproof is now added in 1.2.5 thanks to @nobodywasishere's [spreadsheet](https://docs.google.com/spreadsheets/d/1bx6RvTCEGn5zA06lW_uZGZ_dq6qQyCZC_NifmyeC1lM/edit?usp=sharing) and permission for usage
