### ISSUE TITLE
Please add the count of maintainers and a filter for it

### ISSUE THREAD

**Issue by jedie** [bucherfa/lineageos-devices#10]
Hi, i'm the maintainer of https://github.com/jedie/lineageos_info ... Think one important information are the count of the official maintainer of every device.

The idea is simple: the more maintainers there are, the more likely a longer support period is.

![grafik](https://user-images.githubusercontent.com/71315/105635326-7f458300-5e62-11eb-9ad5-49ad588fb53c.png)

see: https://github.com/jedie/lineageos_info#top-10-devices

Would be great if you add this information in your project! Then i will discontinue my project ;)

**Comment by bucherfa** [comment]
Hey @jedie,

thank you for your suggestion.

The amount per device of maintainers is displayed in the purple bubble underneath the device name. You can sort by maintainer count with the sort by dropdown menu, selecting `Maintainers (descending)`.

Is that what you are looking for?

**Comment by nobodywasishere** [comment]
@jedie 

> The idea is simple: the more maintainers there are, the more likely a longer support period is.

I do not believe this is a correct assumption.
