### ISSUE TITLE
suggestions: add connectivity filter

### ISSUE THREAD

**Issue by bjacquin** [bucherfa/lineageos-devices#12]
Hi,

Thank you for this effort, this is greatly appreciated.

Some users may also want to select a phone if it supports 4G or 5G, would it be possible to add a filter to support this ?

Thanks,
Bertrand

**Comment by bucherfa** [comment]
Hi @bjacquin,

thank you for your suggestion. It is now implemented.

see 2def619870551020b22efc1d4170994c4fd3f5c0 for details

let me know what you think. :)

**Comment by bjacquin** [comment]
Wonderful, thanks a lot!
