### ISSUE TITLE
Suggestion: filter by dimensions

### ISSUE THREAD

**Issue by alfonsodelavega** [bucherfa/lineageos-devices#2]
I'd like to say congrats, this is a very nice and useful tool!

One thing I miss is the ability to filter by dimensions, which is something I usually do when searching for reasonably sized phones.

I noticed that the dimension properties are not present for some devices, but they are for others. Could this filter be included to do a "best effort" though?

**Comment by bucherfa** [comment]
Thanks, I am glad you like it.

I think I will add dimensions in the next couple of weeks. Don't know yet how I would handle phones without this data, will see about that.

**Comment by bucherfa** [comment]
The dimensions have been added in 1.2.6.

Luckily I could use the [data](https://docs.google.com/spreadsheets/d/1bx6RvTCEGn5zA06lW_uZGZ_dq6qQyCZC_NifmyeC1lM/edit?usp=sharing) from @nobodywasishere to fill in the missing dimensions, so no problem there.

Feel free to try it out and to give feedback.

**Comment by alfonsodelavega** [comment]
Works really well, thank you!

Searching mobiles by length is very common in this era of phones big as shoes.

Cheers.
