### ISSUE TITLE
Add USB port type please

### ISSUE THREAD

**Issue by deoxal** [bucherfa/lineageos-devices#23]
Micro type B USB connectors have a tendency to put more stress on the exterior eventually causing a crack near the port. For that reason I'd like to see the devices filterable by port type.

**Comment by bucherfa** [comment]
I would love to add this, unfortunately I have no easy way to source that information. most data I get from https://github.com/LineageOS/lineage_wiki/tree/master/_data/devices, which doesn't include the USB connector type.

**Comment by deoxal** [comment]
Could you scrape it from GSMArena? That's where I always cross reference from.

**Comment by bucherfa** [comment]
that would be a whole new project. if the data was already scraped and available as in a usable data format (json or similar) with a code names <=> GSMArena entry mapping, then I would consider it.
Otherwise I don't have the time for this right now. :/
