### ISSUE TITLE
Please Update the Site

### ISSUE THREAD

**Issue by curiousrom** [bucherfa/lineageos-devices#25]
Hello, I love your site http://www.lineageosdevices.com/ but the problem is that @ the present bottom left it says: Data last updated: 2022-04-26.

If you filter by Versions 19.1 it returns "41 Devices matching" but in the LineageOS official https://github.com/LineageOS/hudson/blob/master/lineage-build-targets there is 75 devices supported with 19.1 @ the present.

**Comment by bucherfa** [comment]
Hi @curiousrom, thank you for reminding me. The site is now up to date again. :)

**Comment by curiousrom** [comment]
Thank you!
