### ISSUE TITLE
Maintaners label click trough on github timeline?

### ISSUE THREAD

**Issue by MartinN3** [bucherfa/lineageos-devices#26]
Maintenance could link to github repo, where one could make more informed decision of contribution by each contributor. Reasoning is: number of maintainers can fluctuate as can quality. There could be simply link to github repo:

for instance phone One Plus 9 pro it could be this page - https://github.com/LineageOS/android_device_oneplus_lemonadep/graphs/contributors 

or 

https://review.lineageos.org/q/lemonadep

**Comment by bucherfa** [comment]
thanks for the idea, I like it

will look into it soon...
