### ISSUE TITLE
Please Update the Site - Automated?

### ISSUE THREAD

**Issue by curiousrom** [bucherfa/lineageos-devices#27]
Hello, I love your site http://www.lineageosdevices.com/ but the problem is that @ the present bottom left it says: Data last updated: 2022-07-26.

If you filter by Versions 19.1 it returns "75 Devices matching" but in the LineageOS official https://github.com/LineageOS/hudson/blob/master/lineage-build-targets there is 92 devices supported with 19.1 @ the present.

In fact there are more changes than that because some devices were removed while other were added as seen in https://review.lineageos.org/q/project:LineageOS/hudson+-abandoned

I reported something similar in https://github.com/bucherfa/lineageos-devices/issues/25 an you updated it.

Maybe the update process could be automated?

**Comment by bucherfa** [comment]
I'm glad you enjoy the site :heart: 

site is updated, will look into automatically updating the site soon :)

**Comment by curiousrom** [comment]
**BIG THANKS!**
