### ISSUE TITLE
Add headphone jack filter

### ISSUE THREAD

**Issue by toastal** [bucherfa/lineageos-devices#29]
I’ve been in the market for a new phone due to lack of security upgrades on current phone, and “has headphone jack” is one of the highest priorities to me—along with OLED display (issue #22) @ 100% DCI-P3 coverage. Both of which are covered by my current phone and anything else would be considered a downgrade.

Bluetooth is finicky and good to disable by default for security. Bluetooth earbuds require batteries/charging, are difficult or impossible to repair (leading to e-waste), and I already have good IEMs. Lightweight dongles make you choose between charging and audio, and the ones with power delivery are bulky. All of these concerns are ameliorated with the presence of a headphone jack (3.5mm or balanced 4.4mm could be a granularity improvement).

**Comment by bucherfa** [comment]
same as #33
