### ISSUE TITLE
extra/data.json is not found

### ISSUE THREAD

**Issue by nobodywasishere** [bucherfa/lineageos-devices#3]
(I am assuming this file contains all of the information about every device, and that it is either supposed to be generated by the server pulling information from wiki.lineageos.org or it is manually curated.)

Was this file not included on purpose? If so, that's okay. I am unable to successfully start a localhost version of the server as the file does not exist.

**Comment by bucherfa** [comment]
sorry, my mistake.

forgot to add to the readme how to generate the data.

```bash
npm run update:data
```

but make sure to pull the repo before once again, since i adjusted the script a bit

```bash
git pull
```

**Comment by bucherfa** [comment]
the latest device made some parsing problems, but now it is adjusted as well.

so updating data and running it locally should work again.

**Comment by nobodywasishere** [comment]
Thank you!
