### ISSUE TITLE
Devices with 18.1

### ISSUE THREAD

**Issue by JensKorte** [bucherfa/lineageos-devices#32]
The 32 bit devices that don't get past 18.1 [1] [2]. They still get updates and even new devices will be added. Please add (maintained) 18.1 devices.
Thanks for the website.

[1] https://source.android.com/docs/core/architecture/kernel/bpf?hl=de
[2] https://lineageos.org/Changelog-27/#deprecations.

**Comment by bucherfa** [comment]
for some old devices there were [data inconsistencies](https://github.com/LineageOS/lineage_wiki/tree/master/_data/devices) which made me filter out all but the most up-to-date Lineage version. I will occasionally check if I can re-enable all actively maintained devices.
