### ISSUE TITLE
Feature request: add headphone jack as a feature

### ISSUE THREAD

**Issue by Darin755** [bucherfa/lineageos-devices#33]
With today's phones seeming to want to kill the headphone jack it is becoming harder and harder to find a device with a headphone jack.

Would it be possible to add that is a feature?

**Comment by Soundtoxin** [comment]
Came here to request this. Also, I swear earlier versions of the site actually had this as something you could filter by...

**Comment by bucherfa** [comment]
unfortunately same situation as #34 

the information was previously sourced from a [different data source](https://docs.google.com/spreadsheets/d/1bx6RvTCEGn5zA06lW_uZGZ_dq6qQyCZC_NifmyeC1lM/edit#gid=1120211752) which is no longer maintained
