### ISSUE TITLE
[feature request] Notification LED as filter option

### ISSUE THREAD

**Issue by Wurzelmann** [bucherfa/lineageos-devices#34]
Hi,

would it be possible to add "notification LED" as filter option? It seems fewer and fewer phones have these, which is a shame IMO and being able to filter for it would greatly improve the search.

Thanks in advance!

**Comment by bucherfa** [comment]
thank you for the request. Currently the only data source is the [raw data from the wiki](https://github.com/LineageOS/lineage_wiki/tree/master/_data/devices). Since there is no indicator if a device has a notification LED I can currently not add it as a filter. :(
