### ISSUE TITLE
Rename Release to Release Date, or something else?

### ISSUE THREAD

**Issue by davralin** [bucherfa/lineageos-devices#8]
Was scrolling through the page, and my initial thoughts were "this would be perfect if I could sort and find the newest released phone".

After going at it for a while I realized that `Release` means release date, and not the date of the LoS-build.

This might just be my opinion, and it is kinda obvious from the date on it - but I just wanted to give it as a feedback.

**Comment by bucherfa** [comment]
Thank you for your feedback.

True, you are right, `Release date` makes in clearer. I made the adjustment. :)

**Comment by davralin** [comment]
Thanks, looks good! :-)
